---
image: docker:latest

services:
  - docker:dind

before_script:
  - set -eux
  - echo http://dl-cdn.alpinelinux.org/alpine/edge/testing \
    >> /etc/apk/repositories
  - echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" \
    >> /etc/apk/repositories
  - apk update
  - apk add git sbt
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  - git clone https://github.com/codeoverflow-org/chatoverflow.git
  - cd chatoverflow
  - git submodule add -f \
    https://github.com/codeoverflow-org/chatoverflow-api.git api
  - git submodule add -f \
    https://github.com/codeoverflow-org/chatoverflow-plugins.git plugins-public
  - git submodule init
  - git submodule update
  - sbt clean
  - sbt fetch
  - sbt reload
  - sbt version
  - sbt doc
  - cd ..

build:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
