---
image: williamyeh/java8:latest

before_script:
  - echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
  - apt-get update
  - apt-get install git docker scala sbt
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  - git clone https://github.com/codeoverflow-org/chatoverflow.git
  - cd chatoverflow
  - git submodule add https://github.com/codeoverflow-org/chatoverflow-api.git api
  - git submodule add https://github.com/codeoverflow-org/chatoverflow-plugins.git plugins-public
  - git submodule init
  - git submodule update
  - sbt clean
  - sbt fetch
  - sbt reload
  - sbt version
  - sbt doc
  - cd ..

build:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
